{% set version = "0.1.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-unigd
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/unigd_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/unigd/unigd_{{ version }}.tar.gz
  sha256: 1df76ab42fa3ab4cbf1c8e27aabeb352e939a5b861f6853987e8b8daf73b0ab3
  patches:
    - patches/0001-minimal-ucrt-libs.patch

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]
  skip: true  # [ppc64le]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-cpp11 >=0.2.4              # [build_platform != target_platform]
    - r-systemfonts >=1.0.0        # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib('c') }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib('m2w64_c') }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-cpp11 >=0.2.4
    - r-systemfonts >=1.0.0
    - cairo
    - libpng
    - libtiff
    - zlib
  run:
    - r-base
    - r-cpp11 >=0.2.4
    - r-systemfonts >=1.0.0

test:
  commands:
    - $R -e "library('unigd')"           # [not win]
    - "\"%R%\" -e \"library('unigd')\""  # [win]

about:
  home: https://nx10.github.io/unigd/
  dev_url: https://github.com/nx10/unigd
  license: GPL-2.0-or-later
  summary: A unified R graphics backend. Render R graphics fast and easy to many common file formats. Provides a thread safe 'C' interface for asynchronous rendering of R graphics.
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
    - {{ environ["SRC_DIR"] }}/inst/licenses/fmt-MIT.txt
    - {{ environ["SRC_DIR"] }}/inst/licenses/svglite-GPL-2.txt

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: unigd
# Type: Package
# Title: Universal Graphics Device
# Version: 0.1.2
# Authors@R: c( person(given = "Florian", family = "Rupprecht", email = "floruppr@gmail.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-1795-8624")), person(given = "Kun", family = "Ren", role = "ctb", email = "mail@renkun.me"), person(given = "Tatsuya", family = "Shima", role = "ctb", email = "ts1s1andn@gmail.com"), person("Jeroen", "Ooms", role = c("ctb"), email = "jeroen@berkeley.edu", comment = c(ORCID = "0000-0002-4035-0289")), person("Hadley", "Wickham", email = "hadley@rstudio.com", role = "cph", comment = "Author of included svglite code"), person("Lionel", "Henry", email = "lionel@rstudio.com", role = "cph", comment = "Author of included svglite code"), person("Thomas Lin", "Pedersen", email = "thomas.pedersen@rstudio.com", role = "cph", comment = "Author and creator of included svglite code"), person("T Jake", "Luciani", email = "jake@apache.org", role = "cph", comment = "Author of included svglite code"), person("Matthieu", "Decorde", email = "matthieu.decorde@ens-lyon.fr", role = "cph", comment = "Author of included svglite code"), person("Vaudor", "Lise", email = "lise.vaudor@ens-lyon.fr", role = "cph", comment = "Author of included svglite code"), person("Tony", "Plate", role = "cph", comment = "Contributor to included svglite code"), person("David", "Gohel", role = "cph", comment = "Contributor to included svglite code"), person("Yixuan", "Qiu", role = "cph", comment = "Contributor to included svglite code"), person("Hakon", "Malmedal", role = "cph", comment = "Contributor to included svglite code"), person("RStudio", role = "cph", comment = "Copyright holder of included svglite code"), person("Brett", "Robinson", role = "cph", comment = "Author of included belle library"), person("Google", role = "cph", comment = "Copyright holder of included material design icons"), person("Victor", "Zverovich", role = "cph", comment = "Author of included fmt library"), person("Andrzej", "Krzemienski", role = "cph", comment = "Author of included std::experimental::optional library") )
# Description: A unified R graphics backend. Render R graphics fast and easy to many common file formats. Provides a thread safe 'C' interface for asynchronous rendering of R graphics.
# License: GPL (>= 2)
# Depends: R (>= 3.2.0)
# Imports: systemfonts (>= 1.0.0)
# LinkingTo: cpp11 (>= 0.2.4), systemfonts
# Encoding: UTF-8
# SystemRequirements: libpng, cairo, freetype2, fontconfig
# RoxygenNote: 7.3.0
# URL: https://github.com/nx10/unigd, https://nx10.github.io/unigd/
# BugReports: https://github.com/nx10/unigd/issues
# Suggests: testthat (>= 3.0.0), xml2 (>= 1.0.0), fontquiver (>= 0.2.0), covr, knitr, rmarkdown
# Config/testthat/edition: 3
# Config/Needs/website: tidyverse/tidytemplate
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Packaged: 2024-06-05 20:30:05 UTC; floru
# Author: Florian Rupprecht [aut, cre] (<https://orcid.org/0000-0002-1795-8624>), Kun Ren [ctb], Tatsuya Shima [ctb], Jeroen Ooms [ctb] (<https://orcid.org/0000-0002-4035-0289>), Hadley Wickham [cph] (Author of included svglite code), Lionel Henry [cph] (Author of included svglite code), Thomas Lin Pedersen [cph] (Author and creator of included svglite code), T Jake Luciani [cph] (Author of included svglite code), Matthieu Decorde [cph] (Author of included svglite code), Vaudor Lise [cph] (Author of included svglite code), Tony Plate [cph] (Contributor to included svglite code), David Gohel [cph] (Contributor to included svglite code), Yixuan Qiu [cph] (Contributor to included svglite code), Hakon Malmedal [cph] (Contributor to included svglite code), RStudio [cph] (Copyright holder of included svglite code), Brett Robinson [cph] (Author of included belle library), Google [cph] (Copyright holder of included material design icons), Victor Zverovich [cph] (Author of included fmt library), Andrzej Krzemienski [cph] (Author of included std::experimental::optional library)
# Maintainer: Florian Rupprecht <floruppr@gmail.com>
# Repository: CRAN
# Date/Publication: 2024-06-05 21:40:02 UTC
